---
- name: Installer Nginx via Homebrew
  community.general.homebrew:
    name: nginx
    state: present

- name: Créer le template de configuration Nginx pour Symfony
  ansible.builtin.copy:
    content: |
      server {
          listen 8080;
          server_name {{ web_server_name }};
          root {{ symfony_root_dir | realpath }}/public;

          # Logs détaillés
          error_log /opt/homebrew/var/log/nginx/{{ web_server_name }}_error.log debug;
          access_log /opt/homebrew/var/log/nginx/{{ web_server_name }}_access.log combined;

          location / {
              try_files $uri /index.php$is_args$args;
          }

          location ~ ^/index\.php(/|$) {
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_split_path_info ^(.+\.php)(/.*)$;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param DOCUMENT_ROOT $document_root;
              fastcgi_buffer_size 128k;
              fastcgi_buffers 4 256k;
              fastcgi_busy_buffers_size 256k;
              internal;
          }

          # Exception pour le fichier test.php
          location = /test.php {
              fastcgi_pass 127.0.0.1:9000;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root/test.php;
              fastcgi_param DOCUMENT_ROOT $document_root;
          }

          location ~ \.php$ {
              return 404;
          }

          client_max_body_size 20M;
          client_body_buffer_size 128k;
      }
    dest: "/opt/homebrew/etc/nginx/servers/{{ web_server_name }}.conf"
    mode: '0644'

- name: Redémarrer Nginx
  ansible.builtin.shell: |
    sudo /opt/homebrew/bin/nginx -s stop || true
    sleep 2
    sudo /opt/homebrew/bin/nginx
  become: true
