name: "Déploiement Automatique"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: "Déploiement avec Ansible"
    # Exécuter uniquement si la PR a été mergée (pas fermée sans merge)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup SSH Key"
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "9.3.0"
  
      - name: "Print Ansible version"
        run: ansible-playbook --version

      - name: "Create Ansible inventory"
        run: |
          mkdir -p infrastructure/ansible/ssh_keys
          echo "[vps]" > infrastructure/ansible/inventory.ci.ini
          echo "${{ secrets.VPS_HOST }} ansible_user=${{ secrets.VPS_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> infrastructure/ansible/inventory.ci.ini
          cat infrastructure/ansible/inventory.ci.ini

      - name: "Deploy with Ansible"
        run: |
          cd infrastructure/ansible
          ansible-playbook playbooks/symfony_stack.yml -i inventory.ci.ini 